
name: 'ktlint-check'
description: 'Run ktlint to check your code and annotate pull requests with errors'
author: 'Anton Musichin'
branding:
  icon: 'check'
  color: 'orange'
inputs:
  ktlint-version:
    required: true
    default: '0.50.0'
    description: 'Version of ktlint, e.g. "0.50.0"'
  level:
    required: true
    default: 'error'
    description: 'Annotation level for lint errors. Possible values: "error", "warning", "notice", "none"'


  # use "ktlint --help" for more information
  patterns:
    required: false
  code-style:
    required: false
  disabled_rules:
    required: false
  format:
    required: false
  limit:
    required: false
  relative:
    required: false
  reporter:
    required: false
  ruleset:
    required: false
  editorconfig:
    required: false
  experimental:
    required: false
  baseline:
    required: false
  log-level:
    required: false
  android:
    required: false
    deprecationMessage: code-style
  debug:
    required: false
    deprecationMessage: log-level
  trace:
    required: false
    deprecationMessage: log-level
  verbose:
    required: false
    deprecationMessage: log-level
runs:
  using: 'node16'
  main: 'dist/index.js'
