
name: 'ktlint-check'
description: 'Run ktlint to check your code and annotate pull requests with errors'
author: 'Anton Musichin'
branding:
  icon: 'check'
  color: 'orange'
inputs:
  ktlint-version:
    required: true
    default: '0.46.1'
    description: 'Version of ktlint, e.g. "0.46.1".'
  level:
    required: true
    default: error
    description: 'Annotation level for lint errors. Possible values: "error", "warning", "notice", "none".'

  # use "ktlint --help" for more information
  android:
    required: false
  debug:
    required: false
  disabledRules:
    required: false
  format:
    required: false
  limit:
    required: false
  relative:
    required: false
  reporter:
    required: false
  ruleset:
    required: false
  editorconfig:
    required: false
  experimental:
    required: false
  baseline:
    required: false
  patterns:
    required: false
  verbose:
   required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
